export const USERS_SEARCH_REQUEST = "USERS_SEARCH_REQUEST";
export const USERS_SEARCH_SUCCESS = "USERS_SEARCH_SUCCESS";
export const USERS_SEARCH_FAIL = "USERS_SEARCH_FAIL";
export const USERS_SEARCH_CLEAR = "USERS_SEARCH_CLEAR";
